git: Switch from aanand/git-up to msiemens/PyGitUp
aanand/git-up is no longer maintained and does not work with the latest Ruby
version:

    posix-spawn.c:226:34: error: passing argument 2 of ‘rb_hash_foreach’ from
    incompatible pointer type [-Wincompatible-pointer-types]